package com.test.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.Contact;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration  //springboot的配置标签，启动spring的时候会自动启动配置标签
@EnableSwagger2 //启用 swagger2
public class SwaggerConfig
{
    @Bean
    //Docket:目录
    public Docket api()
    {
        return new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo()).pathMapping("/")
                .select().paths(PathSelectors.regex("/.*")).build();
    }

    //info：信息
    private ApiInfo apiInfo()
    {
        //contact:联络人
        return new ApiInfoBuilder().title("my API document")
                .contact(new Contact("hansen",",","279745791@qq.com"))
                .description("here's the API documentation generated by my swaggerui")
                .version("1.0.0.0").build();
    }
    //最后访问信息为：
    //localhost:8898/swagger-ui.html
}
